title:        API Encryption
url:          http://encryption.apievangelist.com
raw_url: http://encryption.apievangelist.com/apis/

tag: Encryption

logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-logo-api-encryption.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

github_user: api-evangelist
github_repo: encryption
github_branch: gh-pages

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60
