swagger: "2.0"
info:
  title: API Evangelist Patents (2016)
  description: These are the patents for this year, filtered by area.
  version: 1.0.0
host: patents.2016.apievangelist.com
basePath: /apis
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /all/:
    get:
      summary: Get all patents.
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /database/:
    get:
      summary: Get database API patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /definitions/:
    get:
      summary: Get API definition patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /deployment/:
    get:
      summary: Get API deployment patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /design/:
    get:
      summary: Get API design patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /hypermedia/:
    get:
      summary: Get hypermedia API patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /machine-learning/:
    get:
      summary: Get machine learning API patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /management/:
    get:
      summary: Get API management patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /microservice/:
    get:
      summary: Get microservice patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /monitoring/:
    get:
      summary: Get API monitoring patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /network/:
    get:
      summary: Get network API patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /performance/:
    get:
      summary: Get API performance patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /portal/:
    get:
      summary: Get API portal patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /proxy/:
    get:
      summary: Get API proxy patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /search/:
    get:
      summary: Get API search patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /security/:
    get:
      summary: Get API security patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /serverless/:
    get:
      summary: Get serverless API patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /terms-of-service/:
    get:
      summary: Get API terms of service patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /testing/:
    get:
      summary: Get API testing patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /versioning/:
    get:
      summary: Get API versioning patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /virtualization/:
    get:
      summary: Get API virtualization patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
  /webhooks/:
    get:
      summary: Get webhook patents
      description: Returns all the patents for this year.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/patent'
      tags:
        - Patents
definitions:
  patent:
    properties:
      title:
        description: The title of the patent
        type: string
      publication_date:
        description: The publication date of the patent.
        type: string
      number:
        description: The patent number.
        type: string
      url:
        description: The url for the patent.
        type: string
      abstract:
        description: The abstract of the patent.
        type: string
      owner:
        description: The owner of the patent.
        type: string
      owner_city:
        description: The city for the owner of the patent.
        type: string
      owner_country:
        description: The country for the the owner of the patent.
        type: string
